### PR TITLE
Bump diffusers from `0.24` to `0.26`

### PR DESCRIPTION
**Pull request by longgui0318**
from https://github.com/levihsu/OOTDiffusion/issues/44#issuecomment-1968365131

### CODE REVIEW

**Comment by longgui0318** [comment]
I've verified that this modification supports 0.26.3 diffusers properly.

**Comment by iyume** [comment]
Is this meant to upgrade diffusers to `0.26.3`?

**Comment by iyume** [comment]
Seems this is a dependency upgradation. You should lock the diffusers to `0.26`.

**Comment by longgui0318** [comment]
ok

**Comment by iyume** [comment]
Meantime, I have add a new branch https://github.com/AuroBit/ComfyUI-OOTDiffusion/tree/diffusers-0.26 to keep both `0.24` (default branch) and `0.26` (diffusers-0.26 branch).

Please set your PR target to `diffusers-0.26`.

**Comment by longgui0318** [comment]
@iyume  done.

I checked the code and there was no upgrade to 0.26.0 just an increase in the minimum version requirement

**Comment by iyume** [comment]
A version `MAJOR.MINOR.PATCH` changed in `PATCH` shouldn't have breaking changes. Maybe `diffusers>=0.25`?

**Comment by longgui0318** [comment]
不太清楚，但目前的两个类最低0.25.1就行。我提交记录里面有写详细的id

**Comment by iyume** [comment]
`GLIGENTextBoundingboxProjection` is introduced at `diffusers>=0.26`

You should lock diffusers with `diffusers~=0.26.0`

**Comment by longgui0318** [comment]
> You should lock diffusers with `diffusers~=0.26.0`

yes ,you are right. i fix it.

**Comment by longgui0318** [comment]
However, I would advise against using a branching approach to maintain this release, as most users are not developers. They may not be aware of this switching branch. At the same time, this community is very active and doesn't have a lot of baggage to have to do to be forward compatible, diffusers do, not to mention us plugins!

**Comment by iyume** [comment]
This is a design problem for ComfyUI itself, not a problem of ComfyUI community. ComfyUI doesn't take the advantage of python package management system to its plugins, which can easily lead to ambitrary dependency conflicts. If I change the dependency at this time, the user would have to do `git pull` and `pip install -U` at the same time. (Even I could detect the environment in my code and give user upgrade suggestion. It is not good to do this frequently)

If the official OOTDiffusion upgrade, I would upgrade at the same time.

**Comment by julien-blanchon** [comment]
Could you merge to main ?

**Comment by sdduythai** [comment]
hi, I tried installing both [main] and [diffusers-0.26] with diffusers-0.24. However, it make error: 
  File "F:\test\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\test\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "F:\test\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\inference_ootd.py", line 23, in <module>
    from .pipelines_ootd.pipeline_ootd import OotdPipeline
  File "F:\test\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\pipeline_ootd.py", line 27, in <module>
    from .unet_vton_2d_condition import UNetVton2DConditionModel
  File "F:\test\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\unet_vton_2d_condition.py", line 23, in <module>
    from .unet_vton_2d_blocks import (
  File "F:\test\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\unet_vton_2d_blocks.py", line 23, in <module>
    from .transformer_vton_2d import Transformer2DModel
  File "F:\test\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\transformer_vton_2d.py", line 29, in <module>
    from diffusers.models.embeddings import CaptionProjection, PatchEmbed
**ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings'** (F:\test\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)

Cannot import F:\test\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' (F:\test\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)
Traceback (most recent call last):
  File "F:\test\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\test\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion-diffusers-0.26\__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "F:\test\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion-diffusers-0.26\inference_ootd.py", line 16, in <module>
    from . import pipelines_ootd
**ModuleNotFoundError: No module named 'ComfyUI-OOTDiffusion-diffusers-0'**

Cannot import F:\test\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion-diffusers-0.26 module for custom nodes: No module named 'ComfyUI-OOTDiffusion-diffusers-0'
How i can fix it?

**Pull request merged**
